name: chaotic-dreams

dependencies:
  - python=3.9.1
  - h5py
  - jupyter
  - matplotlib
  - nomkl
  - numpy
  - openpyxl
  - pandas
  - requests
  - scikit-learn
  - scipy
  - conda-forge::statsmodels
  - tqdm
  - pip
  - pip:
    - cython
    - mne
